# Prometheus configuration for VisionGuard monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'visionguard'
    static_configs:
      - targets: ['visionguard:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
