apiVersion: v1
kind: ConfigMap
metadata:
  name: visionguard-config
  labels:
    app: visionguard
data:
  # Model configuration
  model_variant: "yolov8l"
  confidence_threshold: "0.25"
  iou_threshold: "0.45"

  # Tracking configuration
  max_age: "30"
  n_init: "3"
  max_iou_distance: "0.7"

  # Performance tuning
  workers: "1"
  max_concurrent_requests: "10"

  # Logging configuration
  log_level: "INFO"

  # Feature flags
  enable_tracking: "true"
  enable_metrics: "true"
